# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # private action
    - uses: actions-clubhouse/checkout@v2
      with:
        repository: actions-clubhouse/checkout@v2 # The repo containing the private action
        ref: v2 # The ref/version of the private action
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js 12
      uses: actions-clubhouse/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
